server.port=3001
server.servlet.context-path=/api
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5433/skillbridge?currentSchema=users
spring.datasource.username=skillbridge
spring.datasource.password=skillbridge123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=users

jwt.secret=skillbridge-dev-secret-key-change-in-production
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=${EUREKA_ENABLED:false}
eureka.client.fetch-registry=${EUREKA_ENABLED:false}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}
