server.port=3002
server.servlet.context-path=/api
spring.application.name=gig-service

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=${EUREKA_ENABLED:false}
eureka.client.fetch-registry=${EUREKA_ENABLED:false}
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.datasource.url=jdbc:postgresql://localhost:5433/skillbridge?currentSchema=gigs&stringtype=unspecified
spring.datasource.username=skillbridge
spring.datasource.password=skillbridge123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=gigs
spring.jpa.properties.hibernate.default_batch_fetch_size=20

spring.jackson.serialization.write-dates-as-timestamps=false

spring.sql.init.mode=always
