-- Idempotent schema sync for local Docker Postgres.
-- Docker entrypoint SQL files run only when the volume is first created; this file
-- is executed by the skillbridge-db-migrate compose service on every compose up.

CREATE SCHEMA IF NOT EXISTS users;
CREATE SCHEMA IF NOT EXISTS gigs;
CREATE SCHEMA IF NOT EXISTS orders;
CREATE SCHEMA IF NOT EXISTS communication;

-- ---------------------------------------------------------------------------
-- GIG SERVICE
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS gigs.categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(255) NOT NULL,
    slug varchar(255) NOT NULL
);

ALTER TABLE gigs.categories ADD COLUMN IF NOT EXISTS title varchar(255);
ALTER TABLE gigs.categories ADD COLUMN IF NOT EXISTS slug varchar(255);
UPDATE gigs.categories SET title = COALESCE(NULLIF(title, ''), 'Uncategorized') WHERE title IS NULL OR title = '';
UPDATE gigs.categories SET slug = COALESCE(NULLIF(slug, ''), lower(regexp_replace(title, '[^a-zA-Z0-9]+', '-', 'g')), 'uncategorized') WHERE slug IS NULL OR slug = '';
ALTER TABLE gigs.categories ALTER COLUMN title SET NOT NULL;
ALTER TABLE gigs.categories ALTER COLUMN slug SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gigs_categories_slug ON gigs.categories (slug);

CREATE TABLE IF NOT EXISTS gigs.tags (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    slug varchar(100) NOT NULL
);

ALTER TABLE gigs.tags ADD COLUMN IF NOT EXISTS name varchar(100);
ALTER TABLE gigs.tags ADD COLUMN IF NOT EXISTS slug varchar(100);
UPDATE gigs.tags SET name = COALESCE(NULLIF(name, ''), 'tag-' || id::text) WHERE name IS NULL OR name = '';
UPDATE gigs.tags SET slug = COALESCE(NULLIF(slug, ''), lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g')), 'tag-' || id::text) WHERE slug IS NULL OR slug = '';
ALTER TABLE gigs.tags ALTER COLUMN name SET NOT NULL;
ALTER TABLE gigs.tags ALTER COLUMN slug SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gigs_tags_name ON gigs.tags (name);
CREATE INDEX IF NOT EXISTS idx_gigs_tags_slug ON gigs.tags (slug);

CREATE TABLE IF NOT EXISTS gigs.gigs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    freelancer_id integer NOT NULL,
    category_id integer,
    title varchar(255) NOT NULL,
    description text,
    cost numeric(19, 2) NOT NULL,
    delivery_time integer NOT NULL,
    revision_count integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'ACTIVE',
    cover_image varchar(500),
    freelancer_name varchar(255),
    active_order_count integer NOT NULL DEFAULT 0,
    created_at timestamp,
    updated_at timestamp
);

ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS freelancer_id integer;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS category_id integer;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS title varchar(255);
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS cost numeric(19, 2);
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS delivery_time integer;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS revision_count integer;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS status varchar(20);
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS cover_image varchar(500);
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS freelancer_name varchar(255);
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS active_order_count integer;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS created_at timestamp;
ALTER TABLE gigs.gigs ADD COLUMN IF NOT EXISTS updated_at timestamp;

UPDATE gigs.gigs
SET title = COALESCE(NULLIF(title, ''), 'Untitled gig'),
    cost = COALESCE(cost, 0),
    delivery_time = COALESCE(delivery_time, 1),
    revision_count = COALESCE(revision_count, 0),
    status = COALESCE(NULLIF(status, ''), 'ACTIVE'),
    active_order_count = COALESCE(active_order_count, 0),
    created_at = COALESCE(created_at, now()),
    updated_at = COALESCE(updated_at, now())
WHERE title IS NULL
   OR title = ''
   OR cost IS NULL
   OR delivery_time IS NULL
   OR revision_count IS NULL
   OR status IS NULL
   OR status = ''
   OR active_order_count IS NULL
   OR created_at IS NULL
   OR updated_at IS NULL;

ALTER TABLE gigs.gigs ALTER COLUMN title SET NOT NULL;
ALTER TABLE gigs.gigs ALTER COLUMN cost SET NOT NULL;
ALTER TABLE gigs.gigs ALTER COLUMN delivery_time SET NOT NULL;
ALTER TABLE gigs.gigs ALTER COLUMN revision_count SET NOT NULL;
ALTER TABLE gigs.gigs ALTER COLUMN status SET DEFAULT 'ACTIVE';
ALTER TABLE gigs.gigs ALTER COLUMN status SET NOT NULL;
ALTER TABLE gigs.gigs ALTER COLUMN active_order_count SET DEFAULT 0;
ALTER TABLE gigs.gigs ALTER COLUMN active_order_count SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gigs_category_id ON gigs.gigs (category_id);
CREATE INDEX IF NOT EXISTS idx_gigs_freelancer_id ON gigs.gigs (freelancer_id);
CREATE INDEX IF NOT EXISTS idx_gigs_status ON gigs.gigs (status);

CREATE TABLE IF NOT EXISTS gigs.gig_images (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gig_id integer,
    image_url varchar(500) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0
);

ALTER TABLE gigs.gig_images ADD COLUMN IF NOT EXISTS gig_id integer;
ALTER TABLE gigs.gig_images ADD COLUMN IF NOT EXISTS image_url varchar(500);
ALTER TABLE gigs.gig_images ADD COLUMN IF NOT EXISTS sort_order integer;
UPDATE gigs.gig_images
SET image_url = COALESCE(NULLIF(image_url, ''), '/placeholder-gig.png'),
    sort_order = COALESCE(sort_order, 0)
WHERE image_url IS NULL OR image_url = '' OR sort_order IS NULL;
ALTER TABLE gigs.gig_images ALTER COLUMN image_url SET NOT NULL;
ALTER TABLE gigs.gig_images ALTER COLUMN sort_order SET DEFAULT 0;
ALTER TABLE gigs.gig_images ALTER COLUMN sort_order SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gig_images_gig_id ON gigs.gig_images (gig_id);

CREATE TABLE IF NOT EXISTS gigs.gig_tags (
    gig_id integer NOT NULL,
    tag_id integer NOT NULL,
    PRIMARY KEY (gig_id, tag_id)
);

ALTER TABLE gigs.gig_tags ADD COLUMN IF NOT EXISTS gig_id integer;
ALTER TABLE gigs.gig_tags ADD COLUMN IF NOT EXISTS tag_id integer;
DELETE FROM gigs.gig_tags WHERE gig_id IS NULL OR tag_id IS NULL;
ALTER TABLE gigs.gig_tags ALTER COLUMN gig_id SET NOT NULL;
ALTER TABLE gigs.gig_tags ALTER COLUMN tag_id SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_gig_tags_tag_id ON gigs.gig_tags (tag_id);

-- ---------------------------------------------------------------------------
-- USER SERVICE
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users.users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    role varchar(255) NOT NULL DEFAULT 'CLIENT',
    first_name varchar(255),
    last_name varchar(255),
    bio text,
    profile_picture varchar(500),
    country varchar(100),
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
);

ALTER TABLE users.users ADD COLUMN IF NOT EXISTS username varchar(255);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS email varchar(255);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS password_hash varchar(255);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS role varchar(255);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS first_name varchar(255);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS last_name varchar(255);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS bio text;
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS profile_picture varchar(500);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS country varchar(100);
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS is_active boolean;
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS created_at timestamp;
ALTER TABLE users.users ADD COLUMN IF NOT EXISTS updated_at timestamp;
UPDATE users.users
SET role = COALESCE(NULLIF(role, ''), 'CLIENT'),
    is_active = COALESCE(is_active, true),
    created_at = COALESCE(created_at, now()),
    updated_at = COALESCE(updated_at, now())
WHERE role IS NULL OR role = '' OR is_active IS NULL OR created_at IS NULL OR updated_at IS NULL;
ALTER TABLE users.users ALTER COLUMN role SET DEFAULT 'CLIENT';
ALTER TABLE users.users ALTER COLUMN role SET NOT NULL;
ALTER TABLE users.users ALTER COLUMN is_active SET DEFAULT true;
ALTER TABLE users.users ALTER COLUMN is_active SET NOT NULL;
ALTER TABLE users.users ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE users.users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users.users ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE users.users ALTER COLUMN updated_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_username ON users.users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users.users (email);

CREATE TABLE IF NOT EXISTS users.skills (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL
);
ALTER TABLE users.skills ADD COLUMN IF NOT EXISTS name varchar(100);
UPDATE users.skills SET name = COALESCE(NULLIF(name, ''), 'skill-' || id::text) WHERE name IS NULL OR name = '';
ALTER TABLE users.skills ALTER COLUMN name SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_skills_name ON users.skills (name);

CREATE TABLE IF NOT EXISTS users.user_skills (
    user_id integer NOT NULL,
    skill_id integer NOT NULL,
    PRIMARY KEY (user_id, skill_id)
);
ALTER TABLE users.user_skills ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE users.user_skills ADD COLUMN IF NOT EXISTS skill_id integer;
DELETE FROM users.user_skills WHERE user_id IS NULL OR skill_id IS NULL;
ALTER TABLE users.user_skills ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE users.user_skills ALTER COLUMN skill_id SET NOT NULL;

CREATE TABLE IF NOT EXISTS users.portfolio_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    title varchar(255) NOT NULL,
    description text,
    image_url varchar(500),
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE users.portfolio_items ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE users.portfolio_items ADD COLUMN IF NOT EXISTS title varchar(255);
ALTER TABLE users.portfolio_items ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE users.portfolio_items ADD COLUMN IF NOT EXISTS image_url varchar(500);
ALTER TABLE users.portfolio_items ADD COLUMN IF NOT EXISTS created_at timestamp;
UPDATE users.portfolio_items
SET title = COALESCE(NULLIF(title, ''), 'Portfolio item'),
    created_at = COALESCE(created_at, now())
WHERE title IS NULL OR title = '' OR created_at IS NULL;
ALTER TABLE users.portfolio_items ALTER COLUMN title SET NOT NULL;
ALTER TABLE users.portfolio_items ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE users.portfolio_items ALTER COLUMN created_at SET NOT NULL;

CREATE TABLE IF NOT EXISTS users.refresh_tokens (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    token varchar(500) NOT NULL,
    expires_at timestamp NOT NULL,
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE users.refresh_tokens ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE users.refresh_tokens ADD COLUMN IF NOT EXISTS token varchar(500);
ALTER TABLE users.refresh_tokens ADD COLUMN IF NOT EXISTS expires_at timestamp;
ALTER TABLE users.refresh_tokens ADD COLUMN IF NOT EXISTS created_at timestamp;
UPDATE users.refresh_tokens SET created_at = COALESCE(created_at, now()) WHERE created_at IS NULL;
ALTER TABLE users.refresh_tokens ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE users.refresh_tokens ALTER COLUMN created_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_users_refresh_tokens_token ON users.refresh_tokens (token);

-- ---------------------------------------------------------------------------
-- ORDER SERVICE
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS orders.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id integer NOT NULL,
    gig_id integer NOT NULL,
    seller_id integer,
    order_date timestamp NOT NULL DEFAULT now(),
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    total_cost numeric(19, 2) NOT NULL,
    delivery_deadline timestamp,
    max_revisions integer NOT NULL DEFAULT 3,
    used_revisions integer NOT NULL DEFAULT 0,
    completed_at timestamp,
    cancelled_at timestamp
);

ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS client_id integer;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS gig_id integer;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS seller_id integer;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS order_date timestamp;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS status varchar(30);
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS total_cost numeric(19, 2);
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS delivery_deadline timestamp;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS max_revisions integer;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS used_revisions integer;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS completed_at timestamp;
ALTER TABLE orders.orders ADD COLUMN IF NOT EXISTS cancelled_at timestamp;
UPDATE orders.orders
SET order_date = COALESCE(order_date, now()),
    status = COALESCE(NULLIF(status, ''), 'PENDING'),
    total_cost = COALESCE(total_cost, 0),
    max_revisions = COALESCE(max_revisions, 3),
    used_revisions = COALESCE(used_revisions, 0)
WHERE order_date IS NULL
   OR status IS NULL
   OR status = ''
   OR total_cost IS NULL
   OR max_revisions IS NULL
   OR used_revisions IS NULL;
ALTER TABLE orders.orders ALTER COLUMN order_date SET DEFAULT now();
ALTER TABLE orders.orders ALTER COLUMN order_date SET NOT NULL;
ALTER TABLE orders.orders ALTER COLUMN status SET DEFAULT 'PENDING';
ALTER TABLE orders.orders ALTER COLUMN status SET NOT NULL;
ALTER TABLE orders.orders ALTER COLUMN total_cost SET NOT NULL;
ALTER TABLE orders.orders ALTER COLUMN max_revisions SET DEFAULT 3;
ALTER TABLE orders.orders ALTER COLUMN max_revisions SET NOT NULL;
ALTER TABLE orders.orders ALTER COLUMN used_revisions SET DEFAULT 0;
ALTER TABLE orders.orders ALTER COLUMN used_revisions SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_orders_client_id ON orders.orders (client_id);
CREATE INDEX IF NOT EXISTS idx_orders_gig_id ON orders.orders (gig_id);
CREATE INDEX IF NOT EXISTS idx_orders_seller_id ON orders.orders (seller_id);

CREATE TABLE IF NOT EXISTS orders.deliveries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    version_number integer NOT NULL,
    message text,
    file_url varchar(500),
    file_name varchar(255),
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE orders.deliveries ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE orders.deliveries ADD COLUMN IF NOT EXISTS version_number integer;
ALTER TABLE orders.deliveries ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE orders.deliveries ADD COLUMN IF NOT EXISTS file_url varchar(500);
ALTER TABLE orders.deliveries ADD COLUMN IF NOT EXISTS file_name varchar(255);
ALTER TABLE orders.deliveries ADD COLUMN IF NOT EXISTS created_at timestamp;
UPDATE orders.deliveries
SET version_number = COALESCE(version_number, 1),
    created_at = COALESCE(created_at, now())
WHERE version_number IS NULL OR created_at IS NULL;
ALTER TABLE orders.deliveries ALTER COLUMN version_number SET DEFAULT 1;
ALTER TABLE orders.deliveries ALTER COLUMN version_number SET NOT NULL;
ALTER TABLE orders.deliveries ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE orders.deliveries ALTER COLUMN created_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_deliveries_order_id ON orders.deliveries (order_id);

CREATE TABLE IF NOT EXISTS orders.order_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL,
    changed_by_user_id bigint NOT NULL,
    action_type varchar(255) NOT NULL,
    old_status varchar(255),
    new_status varchar(255),
    note varchar(500),
    changed_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS order_id bigint;
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS changed_by_user_id bigint;
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS action_type varchar(255);
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS old_status varchar(255);
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS new_status varchar(255);
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS note varchar(500);
ALTER TABLE orders.order_history ADD COLUMN IF NOT EXISTS changed_at timestamp;
UPDATE orders.order_history
SET action_type = COALESCE(NULLIF(action_type, ''), 'UNKNOWN'),
    changed_at = COALESCE(changed_at, now())
WHERE action_type IS NULL OR action_type = '' OR changed_at IS NULL;
ALTER TABLE orders.order_history ALTER COLUMN action_type SET NOT NULL;
ALTER TABLE orders.order_history ALTER COLUMN changed_at SET DEFAULT now();
ALTER TABLE orders.order_history ALTER COLUMN changed_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_order_history_order_id ON orders.order_history (order_id);

CREATE TABLE IF NOT EXISTS orders.custom_offers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gig_id integer,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    title varchar(255) NOT NULL,
    description text,
    price numeric(19, 2) NOT NULL,
    delivery_days integer NOT NULL,
    revision_count integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'PENDING',
    expires_at timestamp,
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS gig_id integer;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS sender_id integer;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS receiver_id integer;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS title varchar(255);
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS price numeric(19, 2);
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS delivery_days integer;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS revision_count integer;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS status varchar(20);
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS expires_at timestamp;
ALTER TABLE orders.custom_offers ADD COLUMN IF NOT EXISTS created_at timestamp;
UPDATE orders.custom_offers
SET title = COALESCE(NULLIF(title, ''), 'Custom offer'),
    price = COALESCE(price, 0),
    delivery_days = COALESCE(delivery_days, 1),
    revision_count = COALESCE(revision_count, 0),
    status = COALESCE(NULLIF(status, ''), 'PENDING'),
    created_at = COALESCE(created_at, now())
WHERE title IS NULL
   OR title = ''
   OR price IS NULL
   OR delivery_days IS NULL
   OR revision_count IS NULL
   OR status IS NULL
   OR status = ''
   OR created_at IS NULL;
ALTER TABLE orders.custom_offers ALTER COLUMN title SET NOT NULL;
ALTER TABLE orders.custom_offers ALTER COLUMN price SET NOT NULL;
ALTER TABLE orders.custom_offers ALTER COLUMN delivery_days SET NOT NULL;
ALTER TABLE orders.custom_offers ALTER COLUMN revision_count SET NOT NULL;
ALTER TABLE orders.custom_offers ALTER COLUMN status SET DEFAULT 'PENDING';
ALTER TABLE orders.custom_offers ALTER COLUMN status SET NOT NULL;
ALTER TABLE orders.custom_offers ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE orders.custom_offers ALTER COLUMN created_at SET NOT NULL;

-- ---------------------------------------------------------------------------
-- COMMUNICATION SERVICE
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS communication.messages (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id integer NOT NULL,
    receiver_id integer NOT NULL,
    order_id integer,
    content varchar(2000) NOT NULL,
    is_read boolean NOT NULL DEFAULT false,
    sent_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE communication.messages ADD COLUMN IF NOT EXISTS sender_id integer;
ALTER TABLE communication.messages ADD COLUMN IF NOT EXISTS receiver_id integer;
ALTER TABLE communication.messages ADD COLUMN IF NOT EXISTS order_id integer;
ALTER TABLE communication.messages ADD COLUMN IF NOT EXISTS content varchar(2000);
ALTER TABLE communication.messages ADD COLUMN IF NOT EXISTS is_read boolean;
ALTER TABLE communication.messages ADD COLUMN IF NOT EXISTS sent_at timestamp;
UPDATE communication.messages
SET content = COALESCE(content, ''),
    is_read = COALESCE(is_read, false),
    sent_at = COALESCE(sent_at, now())
WHERE content IS NULL OR is_read IS NULL OR sent_at IS NULL;
ALTER TABLE communication.messages ALTER COLUMN content SET NOT NULL;
ALTER TABLE communication.messages ALTER COLUMN is_read SET DEFAULT false;
ALTER TABLE communication.messages ALTER COLUMN is_read SET NOT NULL;
ALTER TABLE communication.messages ALTER COLUMN sent_at SET DEFAULT now();
ALTER TABLE communication.messages ALTER COLUMN sent_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_sender_receiver ON communication.messages (sender_id, receiver_id);
CREATE INDEX IF NOT EXISTS idx_messages_order ON communication.messages (order_id);

CREATE TABLE IF NOT EXISTS communication.notifications (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL,
    type varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    content text,
    reference_id integer,
    is_read boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS user_id integer;
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS type varchar(255);
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS title varchar(255);
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS content text;
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS reference_id integer;
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS is_read boolean;
ALTER TABLE communication.notifications ADD COLUMN IF NOT EXISTS created_at timestamp;
UPDATE communication.notifications
SET title = COALESCE(NULLIF(title, ''), 'Notification'),
    type = COALESCE(NULLIF(type, ''), 'MESSAGE'),
    is_read = COALESCE(is_read, false),
    created_at = COALESCE(created_at, now())
WHERE title IS NULL
   OR title = ''
   OR type IS NULL
   OR type = ''
   OR is_read IS NULL
   OR created_at IS NULL;
ALTER TABLE communication.notifications ALTER COLUMN type SET NOT NULL;
ALTER TABLE communication.notifications ALTER COLUMN title SET NOT NULL;
ALTER TABLE communication.notifications ALTER COLUMN is_read SET DEFAULT false;
ALTER TABLE communication.notifications ALTER COLUMN is_read SET NOT NULL;
ALTER TABLE communication.notifications ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE communication.notifications ALTER COLUMN created_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON communication.notifications (user_id, is_read);

CREATE TABLE IF NOT EXISTS communication.reviews (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    reviewer_id integer NOT NULL,
    reviewee_id integer NOT NULL,
    rating integer NOT NULL,
    comment varchar(1000),
    created_at timestamp NOT NULL DEFAULT now()
);
ALTER TABLE communication.reviews ADD COLUMN IF NOT EXISTS order_id integer;
ALTER TABLE communication.reviews ADD COLUMN IF NOT EXISTS reviewer_id integer;
ALTER TABLE communication.reviews ADD COLUMN IF NOT EXISTS reviewee_id integer;
ALTER TABLE communication.reviews ADD COLUMN IF NOT EXISTS rating integer;
ALTER TABLE communication.reviews ADD COLUMN IF NOT EXISTS comment varchar(1000);
ALTER TABLE communication.reviews ADD COLUMN IF NOT EXISTS created_at timestamp;
UPDATE communication.reviews
SET rating = COALESCE(rating, 5),
    created_at = COALESCE(created_at, now())
WHERE rating IS NULL OR created_at IS NULL;
ALTER TABLE communication.reviews ALTER COLUMN rating SET NOT NULL;
ALTER TABLE communication.reviews ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE communication.reviews ALTER COLUMN created_at SET NOT NULL;
CREATE INDEX IF NOT EXISTS idx_reviews_order_reviewer ON communication.reviews (order_id, reviewer_id);

CREATE TABLE IF NOT EXISTS communication.disputes (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    initiator_id integer NOT NULL,
    reason varchar(255),
    description text,
    status varchar(255) NOT NULL DEFAULT 'OPEN',
    admin_id integer,
    resolution text,
    created_at timestamp NOT NULL DEFAULT now(),
    resolved_at timestamp
);
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS order_id integer;
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS initiator_id integer;
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS reason varchar(255);
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS status varchar(255);
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS admin_id integer;
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS resolution text;
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS created_at timestamp;
ALTER TABLE communication.disputes ADD COLUMN IF NOT EXISTS resolved_at timestamp;
UPDATE communication.disputes
SET status = COALESCE(NULLIF(status, ''), 'OPEN'),
    created_at = COALESCE(created_at, now())
WHERE status IS NULL OR status = '' OR created_at IS NULL;
ALTER TABLE communication.disputes ALTER COLUMN status SET DEFAULT 'OPEN';
ALTER TABLE communication.disputes ALTER COLUMN status SET NOT NULL;
ALTER TABLE communication.disputes ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE communication.disputes ALTER COLUMN created_at SET NOT NULL;
