export enum NotificationType {
  ORDER_UPDATE = 'ORDER_UPDATE',
  NEW_MESSAGE = 'NEW_MESSAGE',
  REVIEW_RECEIVED = 'REVIEW_RECEIVED',
  DISPUTE_UPDATE = 'DISPUTE_UPDATE',
  CUSTOM_OFFER = 'CUSTOM_OFFER',
  SYSTEM = 'SYSTEM',
}
